### PR TITLE
(fix) add env support to common.json config

### PR DESCRIPTION
**Pull request by face**

### CODE REVIEW

**Review by robertkowalski — APPROVED** [review]
the update risk is very low: existing services would need a `production` or `development` key in their `common.json`. in those cases a service would start with a probably changed config.

paolo might know some exceptions?

lgtm so far

**Comment by bariscicek** [comment]
@robertkowalski isn't it only when there is development/production/test keys exist this is relevant? we should not need to update existing services if they are not opt in to separate config. Or am I overlooking something?

**Comment by robertkowalski** [comment]
>  isn't it only when there is development/production/test keys exist this is relevant?

yes thats the only risk i could spot, and it should not happen (tm)

**Comment by prdn** [comment]
It's good.

**Pull request merged**
